#!/usr/bin/env bash
# Install Nginx Server , Configure Index page, add a custome Header

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend webapp
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 421876-web-01 3.83.245.91:80 check
    server 421876-web-02 34.207.188.222:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart