#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# but for the 9th iteration, displays Holberton School and then Hi on a new line.

i=0
while [ $i -ne 10 ]
do
	if [[ i -eq 9 ]]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	counter=$((i - 1))
done